[package]
name = "rcx-admin"
version = "0.1.0"
edition = "2021"

[dependencies]
rcxcore = { path = "../core", features = ["kill-admin"] }
hex = "0.4"
clap = { version = "4.5", features = ["derive"] }
